// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VmcHmi.Infrastructure;

#nullable disable

namespace VmcHmi.Infrastructure.Migrations
{
    [DbContext(typeof(HmiDbContext))]
    partial class HmiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hmi")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VmcHmi.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("checklist_items", "hmi");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.MachineSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_stage");

                    b.Property<string>("OperationStatus")
                        .HasColumnType("text")
                        .HasColumnName("operation_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("machine_sessions", "hmi");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.OperationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("operation_runs", "hmi");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RequiredByItemId")
                        .HasColumnType("text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("tools", "hmi");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "hmi");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("VmcHmi.Domain.Entities.MachineSession", "Session")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.MachineSession", b =>
                {
                    b.HasOne("VmcHmi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.OperationRun", b =>
                {
                    b.HasOne("VmcHmi.Domain.Entities.MachineSession", "Session")
                        .WithOne("OperationRun")
                        .HasForeignKey("VmcHmi.Domain.Entities.OperationRun", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.Tool", b =>
                {
                    b.HasOne("VmcHmi.Domain.Entities.MachineSession", null)
                        .WithMany("Tools")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("VmcHmi.Domain.Entities.MachineSession", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("OperationRun");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
