FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["backend/src/VmcHmi.Api/VmcHmi.Api.csproj", "backend/src/VmcHmi.Api/"]
COPY ["backend/src/VmcHmi.Infrastructure/VmcHmi.Infrastructure.csproj", "backend/src/VmcHmi.Infrastructure/"]
COPY ["backend/src/VmcHmi.Application/VmcHmi.Application.csproj", "backend/src/VmcHmi.Application/"]
COPY ["backend/src/VmcHmi.Domain/VmcHmi.Domain.csproj", "backend/src/VmcHmi.Domain/"]

RUN dotnet restore "backend/src/VmcHmi.Api/VmcHmi.Api.csproj"

COPY . .
WORKDIR "/src/backend/src/VmcHmi.Api"
RUN dotnet publish "VmcHmi.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
EXPOSE 10000
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "VmcHmi.Api.dll"]
